### ISSUE TITLE
got these error

### ISSUE THREAD

**Issue by mithuncoder** [Maxdsdsdsd/dauricum#3]
if isinstance(node.func.value, ast.Call) and node.func.value.func.id in self.bad_names:
AttributeError: 'Attribute' object has no attribute 'id'

**Comment by Maxdsdsdsd** [comment]
i know about these errors, i will fix them today

**Comment by Maxdsdsdsd** [comment]
fixed

**Comment by Maxdsdsdsd** [comment]
fixed
